name: HerbPot
main: herbpot.Main
version: 1.0.0

api-version: 1.16

commands:
    diamining:
        description: ""
        usage: /diamining

    tracer:
        description: ""
        usage: /tracer